### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by melardev** [Zilliqa/dev-portal-old#125]
Hi!

The links to your Bug Bounty program are dead: https://github.com/Zilliqa/dev-portal/blob/master/docs/contributors/contribute-bug-bounty.md

Did you migrate to another platform, or you run a self-hosted BBP or something? Maybe you want to update that page.

**Comment by bb111189** [comment]
Thank you. Fix in #130 

We have move to HackerOne and is scaling up in a private bug bounty. We are likely to open it up in early 2021

**Comment by bb111189** [comment]
Dev portal fixed
